dist: trusty
sudo: required

services: docker

language: bash

branches:
  only:
    - master

before_script:
  - env | sort
  - dir="images/${VERSION}/${VARIANT}"

script:
  - cd "$dir"
  - travis_retry travis_wait 60 docker-compose build
  - docker images
  - travis_retry docker-compose up -d && sleep 60
  - docker-compose ps
  - docker-compose logs
  - docker-compose ps "erpnext_db" | grep "Up" || exit 1
  - docker-compose ps "erpnext_app" | grep "Up" || exit 1
  - docker-compose ps "erpnext_web" | grep "Up" || exit 1
  - echo 'Wait until sites and apps database installed (9-10 minutes)' && sleep 500
  - docker-compose ps
  - docker-compose logs
  - docker-compose ps "erpnext_db" | grep "Up"
  - docker-compose ps "erpnext_app" | grep "Up"
  - docker-compose ps "erpnext_web" | grep "Up"

notifications:
  email: false

matrix:
  allow_failures:
    - env: VERSION=develop VARIANT=alpine
    - env: VERSION=develop VARIANT=stretch-slim
    - env: VERSION=develop VARIANT=stretch
    # FIXME https://github.com/frappe/frappe/issues/7737
    #- env: VERSION=10.x VARIANT=alpine
    #- env: VERSION=10.x VARIANT=stretch-slim
    #- env: VERSION=10.x VARIANT=stretch

env: # Environments
  - VERSION=develop VARIANT=alpine
  - VERSION=develop VARIANT=stretch-slim
  - VERSION=develop VARIANT=stretch
  - VERSION=10.x VARIANT=alpine
  - VERSION=10.x VARIANT=stretch-slim
  - VERSION=10.x VARIANT=stretch
  - VERSION=11.1 VARIANT=alpine
  - VERSION=11.1 VARIANT=stretch-slim
  - VERSION=11.1 VARIANT=stretch
